In [1]:
import numpy as np

In [15]:
a = np.ones((10, 10))
a[0, 0] = 0
print(a)
rows, cols = a.shape
for row in range(rows):
    for col in range(cols):
        if a[row, col] == np.nan:
            print((row, col))

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
a = np.array([1, 2, 3])
a.append(10)
a

AttributeError: 'numpy.ndarray' object has no attribute 'append'